app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cardtown
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: ${CARDTOWN_ADMIN_USERNAME}
        password: ${CARDTOWN_ADMIN_PASSWORD}
        instance:
          service-base-url: http://localhost:8080
          metadata:
            user:
              name: client # todo have these be environment variables
              password: client
  application:
    name: Cardtown Backend Core
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      expose: "*"
      exposure:
        include: "*"
  security:
    enabled: true
    roles: ADMIN
security:
  user:
    name: ${CARDTOWN_ADMIN_USERNAME}
    password: ${CARDTOWN_ADMIN_PASSWORD}
logging:
  file:
    name: core.log
