# just put this on a 9999 without Nginx pointing to it (so it'd be cardtown.co:9999)
server:
  port: 9999
spring:
  application:
    name: Cardtown Admin Server
  security:
    user:
      name: ${CARDTOWN_ADMIN_USERNAME}
      password: ${CARDTOWN_ADMIN_PASSWORD}
