# database
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cardtown
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool-size: 30
spring:
  flyway:
    baseline-on-migrate: true

# reverse proxy
zuul:
  ignoredPatterns: /api/**
  routes:
    frontend:
      path: /**
      url: http://localhost:3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
